---

simulator_configs:

    speed_of_sound: 343.    
    sample_rate: 24000
    segment_seconds: 2.0
    frames_per_sec: 100

    # Environment
    room_length:
        min: 4
        max: 8
    room_width:
        min: 4
        max: 8
    room_height:
        min: 4
        max: 4
    room_margin: 0.2
    collision_raidus: 0.5

    # Sources
    train_audios: "/home/qiuqiangkong/workspaces/nesd/audios/vctk_2s_segments/train"
    test_audios: "/home/qiuqiangkong/workspaces/nesd/audios/vctk_2s_segments/test"
    sources_num:
        min: 0
        max: 2
    source_gain_db:
        min: -20.
        max: 0.
    source_radius: 0.1
    source_apprent_diameter_deg: 10
    
    # Microphones
    mics_yaml: "./microphones/eigenmike_0_0_2.yaml"
    mic_positions_type: "center_of_room"
    # mic_cutoff_freq: 1000
    mic_spatial_irs_path: /home/qiuqiangkong/workspaces/nesd/mic_spatial_irs/rigid_sphere.pkl
    train_mic_noise: "/home/qiuqiangkong/workspaces/nesd/audios/tau_noise/train"
    test_mic_noise: "/home/qiuqiangkong/workspaces/nesd/audios/tau_noise/test"
    noise_gain_db:
        min: 0.
        max: 20.

    # Simulator
    image_source_order: 3

    # Agents
    agent_positions_type: "center_of_mics"  # "random_in_env" | "center_of_mics"
    agent_detection_rays: 
        max_positive: 10
        total: 100 
    agent_distance_rays:
        max_positive: 0
        total: 0
    agent_sep_rays: 
        max_positive: 0
        # max_positive: 0
        total: 0

train:
    device: "cuda"
    num_workers: 32
    # num_workers: 0
    batch_size_per_device: 16
    model_name: NeSD7_srcs_num
    loss_name: detection_bce_srcs_num_ce
    optimizer_name: AdamW
    learning_rate: 1e-3
    save_step_frequency: 1000
