pip install h5py
pip install soundfile
pip install pandas
pip install matplotlib
pip install librosa
pip install pyyaml
pip install ipython
pip install torchaudio
pip install einops
pip install pyroomacoustics