---
task_name: vctk
speed_of_sound: 343.
# dataset_type: DatasetBaseline
sources:
    # source_type: "nigens_official"
    train_hdf5s_dir: "hdf5s/vctk/sr=24000/train"
    test_hdf5s_dir: "hdf5s/vctk/sr=24000/test"
    # classes_num: 15
    min_sources_num: 2
    max_sources_num: 2
    radius: 0.1
    random_position_type: "random_on_unit_sphere"
    projection_type: "parallel_projection"
microphones:
    - world_position: [4, 4, 2]
      position: [0.024327574544, 0.024327574544, 0.024090210327]
      direction: [0.57922796534, 0.57922796534, 0.573576436351]
      directivity: cardioid
    - world_position: [4, 4, 2]
      position: [0.024327574544, -0.024327574544, -0.024090210327]
      direction: [0.57922796534, -0.57922796534, -0.573576436351]
      directivity: cardioid
    - world_position: [4, 4, 2]
      position: [-0.024327574544, 0.024327574544, -0.024090210327]
      direction: [-0.57922796534, 0.57922796534, -0.573576436351]
      directivity: cardioid
    - world_position: [4, 4, 2]
      position: [-0.024327574544, -0.024327574544, 0.024090210327]
      direction: [-0.57922796534, -0.57922796534, 0.573576436351]
      directivity: cardioid
rendering:
    image_source:
        order: 3
    ray_tracing: 
        enable: False
targets:
    position: [4, 4, 2]
    max_loc_rays: 100
    max_sep_rays: 2
    hard_semi_negative: False
    depth_rays: none
train:
    sample_rate: 24000
    input_channels: 1
    output_channels: 1
    segment_seconds: 3.0
    model_type: Model01
    loss_type: intersect_source_bce
    # loss_type: sep_l1
    optimizer_type: AdamW
    learning_rate: 1e-3
    batch_size: 16
    precision: 32
    steps_per_epoch: 10000  # Every 10000 steps is called an `epoch`.
    evaluate_step_frequency: 200     # Evaluate every #evaluate_step_frequency steps.
    save_step_frequency: 2000  # Save every #save_step_frequency steps. 
    early_stop_steps: 200001
    warm_up_steps: 1000
    reduce_lr_steps: 15000
    random_seed: 1234
    resume_checkpoint_path: ""
    classes_num: 15

test:
    segment_seconds: 3.0
    batch_size: 1