---
task_name: vctk
speed_of_sound: 343.
sampler_type: Sampler
dataset_type: DatasetEigenmikeMovSrc
sources:
    train_hdf5s_dir: "hdf5s/vctk/sr=24000/train"
    test_hdf5s_dir: "hdf5s/vctk/sr=24000/test"
    min_sources_num: 2
    max_sources_num: 2
    radius: 0.1
    random_position_type: "random_on_unit_sphere"
    projection_type: "parallel_projection"
    classes_num: 1
train:
    sample_rate: 24000
    input_channels: 1
    output_channels: 1
    segment_seconds: 3.0
    model_type: Model01
    do_localization: True
    do_sed: False
    do_separation: True
    loss_type: loc_bce_sep_l1
    optimizer_type: AdamW
    learning_rate: 1e-3
    batch_size: 16
    precision: 32
    steps_per_epoch: 10000  # Every 10000 steps is called an `epoch`.
    evaluate_step_frequency: 200     # Evaluate every #evaluate_step_frequency steps.
    save_step_frequency: 2000  # Save every #save_step_frequency steps. 
    early_stop_steps: 200001
    warm_up_steps: 1000
    reduce_lr_steps: 15000
    random_seed: 1234
    resume_checkpoint_path: ""
    classes_num: 15

test:
    segment_seconds: 3.0
    batch_size: 1