---
task_name: vctk
speed_of_sound: 343.
sampler_type: Sampler
dataset_type: SedFzLocDatasetDcase2021Task3
sources:
    train_hdf5s_dir: "hdf5s/dcase2019_task3/sr=24000/train"
    test_hdf5s_dir: "hdf5s/dcase2019_task3/sr=24000/test"
    classes_num: 11
train:
    sample_rate: 24000
    input_channels: 1
    output_channels: 1
    segment_seconds: 3.0
    model_type: SedFzLocModel01
    do_localization: True
    do_sed: True
    do_separation: False
    loss_type: classwise_bce_mul_agents
    optimizer_type: AdamW
    learning_rate: 1e-3
    batch_size: 16
    precision: 32
    steps_per_epoch: 10000  # Every 10000 steps is called an `epoch`.
    evaluate_step_frequency: 2000     # Evaluate every #evaluate_step_frequency steps.
    save_step_frequency: 10000  # Save every #save_step_frequency steps. 
    early_stop_steps: 100001
    warm_up_steps: 1000
    reduce_lr_steps: 15000
    random_seed: 1234
    resume_checkpoint_path: ""

test:
    segment_seconds: 3.0
    batch_size: 1